// src/shared/superfoodsCatalogData.js
const superfoodsCatalogData = {
  "moringa-powder": {
    id: "moringa-powder",
    slug: "moringa-powder",
    name: "Moringa Powder",
    image: "/images/superfoods/moringa-powder.jpg",
    description:
      "Nutrient-dense leaf powder rich in vitamins, minerals and antioxidants. Perfect for smoothies and teas.",
    history:
      "Moringa has been used for centuries in traditional Ayurvedic medicine and African healing practices. Known as the 'Miracle Tree' for its extensive health benefits and nutritional value.",
    originCountry: "Nigeria",
    benefits: [
      "Rich in vitamins A, C, and E",
      "High in calcium and iron content",
      "Powerful antioxidant properties",
      "Supports immune system function",
      "Natural energy and vitality boost",
    ],
    prices: { SEK: 0, EUR: 0, USD: 0, GBP: 0 },
    category: "superfoods",
    ingredients: ["100% Moringa oleifera leaf powder"],
    productionYear: "2025",
    bestBefore: "2027",
    naturallyGrown: true,
  },
  "baobab-powder": {
    id: "baobab-powder",
    slug: "baobab-powder",
    name: "Baobab Powder",
    image: "/images/superfoods/baobab-powder.jpg",
    description:
      "Vitamin-C rich fruit pulp powder with prebiotic fiber and a citrus-tangy taste. Excellent for digestive health.",
    history:
      "The Baobab tree, known as the 'Tree of Life' in Africa, has been used for thousands of years in traditional African medicine and nutrition. Its fruit is harvested from ancient trees that can live up to 3,000 years.",
    originCountry: "Nigeria",
    benefits: [
      "Exceptionally high in vitamin C",
      "Prebiotic fiber for gut health",
      "Rich in antioxidants and polyphenols",
      "Supports immune system function",
      "Natural electrolyte balance",
    ],
    prices: { SEK: 0, EUR: 0, USD: 0, GBP: 0 },
    category: "superfoods",
    ingredients: ["100% Baobab (Adansonia digitata) fruit pulp powder"],
    productionYear: "2025",
    bestBefore: "2027",
    naturallyGrown: true,
  },
  "dried-mango": {
    id: "dried-mango",
    slug: "dried-mango",
    name: "Dried Mango",
    image: "/images/superfoods/dried-mango.jpg",
    description:
      "Sweet, chewy dried mango slices with no added sugar. Naturally sun-dried to preserve nutrients and flavor.",
    history:
      "Mango cultivation in Nigeria dates back centuries, with the fruit holding cultural significance in West African traditions. Drying mangoes was a traditional preservation method that allowed communities to enjoy the fruit year-round.",
    originCountry: "Nigeria",
    benefits: [
      "Rich in vitamins A and C",
      "High in dietary fiber",
      "Natural source of antioxidants",
      "Supports eye and skin health",
      "Provides natural energy",
    ],
    prices: { SEK: 0, EUR: 0, USD: 0, GBP: 0 },
    category: "superfoods",
    ingredients: ["100% natural dried mango (Mangifera indica)"],
    productionYear: "2025",
    bestBefore: "2026",
    naturallyGrown: true,
  },
  "dried-pineapple": {
    id: "dried-pineapple",
    slug: "dried-pineapple",
    name: "Dried Pineapple",
    image: "/images/superfoods/dried-pineapple.jpg",
    description:
      "Tropical dried pineapple chunks with natural sweetness. Perfect for snacking or adding to trail mixes.",
    history:
      "Pineapple has been cultivated in tropical regions for centuries. In Nigeria, pineapple farming has become an important agricultural practice, with traditional sun-drying methods preserving the fruit's natural goodness.",
    originCountry: "Nigeria",
    benefits: [
      "Rich in vitamin C and manganese",
      "Contains bromelain enzyme for digestion",
      "Natural anti-inflammatory properties",
      "Supports immune function",
      "Promotes healthy skin and bones",
    ],
    prices: { SEK: 0, EUR: 0, USD: 0, GBP: 0 },
    category: "superfoods",
    ingredients: ["100% natural dried pineapple (Ananas comosus)"],
    productionYear: "2025",
    bestBefore: "2026",
    naturallyGrown: true,
  },
  "dried-papaya": {
    id: "dried-papaya",
    slug: "dried-papaya",
    name: "Dried Papaya",
    image: "/images/superfoods/dried-papaya.jpg",
    description:
      "Sweet and tender dried papaya chunks rich in digestive enzymes. Naturally dried to maintain nutritional value.",
    history:
      "Papaya has been used in traditional medicine across tropical regions for its digestive and healing properties. Nigerian cultivation preserves traditional growing methods while ensuring premium quality.",
    originCountry: "Nigeria",
    benefits: [
      "Rich in papain digestive enzyme",
      "High in vitamins C and A",
      "Supports digestive health",
      "Antioxidant and anti-inflammatory",
      "Promotes skin and eye health",
    ],
    prices: { SEK: 0, EUR: 0, USD: 0, GBP: 0 },
    category: "superfoods",
    ingredients: ["100% natural dried papaya (Carica papaya)"],
    productionYear: "2025",
    bestBefore: "2026",
    naturallyGrown: true,
  },
  "stevia-powder": {
    id: "stevia-powder",
    slug: "stevia-powder",
    name: "Stevia Powder",
    image: "/images/superfoods/stevia-powder.jpg",
    description:
      "Natural zero-calorie sweetener from stevia leaves. Perfect for beverages, baking, and diabetic-friendly recipes.",
    history:
      "Stevia has been used for centuries by indigenous peoples in South America. Modern cultivation in Nigeria adapts this ancient sweetener to tropical conditions while maintaining its natural purity.",
    originCountry: "Nigeria",
    benefits: [
      "Zero calories and zero glycemic impact",
      "Natural alternative to artificial sweeteners",
      "Does not affect blood sugar levels",
      "Tooth-friendly sweetener",
      "Suitable for diabetic diets",
    ],
    prices: { SEK: 0, EUR: 0, USD: 0, GBP: 0 },
    category: "superfoods",
    ingredients: ["100% pure stevia leaf powder (Stevia rebaudiana)"],
    productionYear: "2025",
    bestBefore: "2027",
    naturallyGrown: true,
  },
  "cocoa-powder": {
    id: "cocoa-powder",
    slug: "cocoa-powder",
    name: "Cocoa Powder",
    image: "/images/superfoods/cocoa-powder.jpg",
    description:
      "Rich, dark cocoa powder with intense chocolate flavor. Unprocessed and perfect for beverages and baking.",
    history:
      "Cocoa has deep roots in West African agriculture, with Nigeria being one of the world's cocoa producers. Traditional processing methods preserve the bean's natural antioxidants and flavor compounds.",
    originCountry: "Nigeria",
    benefits: [
      "Rich in flavonoids and antioxidants",
      "Supports cardiovascular health",
      "Natural mood enhancer",
      "High in magnesium and iron",
      "May improve brain function",
    ],
    prices: { SEK: 0, EUR: 0, USD: 0, GBP: 0 },
    category: "superfoods",
    ingredients: ["100% pure cocoa powder (Theobroma cacao)"],
    productionYear: "2025",
    bestBefore: "2027",
    naturallyGrown: true,
  },
  "wild-forest-honey": {
    id: "wild-forest-honey",
    slug: "wild-forest-honey",
    name: "Wild Forest Honey",
    image: "/images/superfoods/wild-forest-honey.jpg",
    description:
      "Raw, unfiltered honey harvested from wild forest regions. Rich in natural enzymes and floral notes.",
    history:
      "Traditional honey harvesting in Nigeria's forests dates back generations, with beekeepers using sustainable methods that respect the natural ecosystem and wild bee populations.",
    originCountry: "Nigeria",
    benefits: [
      "Natural antibacterial and antimicrobial properties",
      "Rich in antioxidants and enzymes",
      "Soothes sore throats and coughs",
      "Natural energy source",
      "Supports digestive health",
    ],
    prices: { SEK: 0, EUR: 0, USD: 0, GBP: 0 },
    category: "superfoods",
    ingredients: ["100% pure wild forest honey"],
    productionYear: "2025",
    bestBefore: "2028",
    naturallyGrown: true,
  },
};

export default superfoodsCatalogData;
