// scripts/generateBlogContent.js
const fs = require("fs-extra");
const path = require("path");
const matter = require("gray-matter");

// ✅ Configurable directory
const postsDir = path.resolve("src/posts");
const outputJson = path.join(postsDir, "posts.json");
const outputJs = path.join(postsDir, "posts.js");

function toCamelCase(slug) {
  return slug
    .replace(/[-_](\w)/g, (_, c) => c.toUpperCase())
    .replace(/^\w/, (c) => c.toLowerCase());
}

async function generateBlogContent() {
  try {
    // ✅ Ensure the posts directory exists
    fs.ensureDirSync(postsDir);

    const files = fs
      .readdirSync(postsDir)
      .filter((file) => file.endsWith(".mdx"));

    if (files.length === 0) {
      console.warn("⚠️ No MDX blog posts found in:", postsDir);
    }

    const posts = [];
    const jsImports = [];
    const jsExports = [];

    for (const file of files) {
      const filePath = path.join(postsDir, file);
      const rawContent = fs.readFileSync(filePath, "utf-8");
      const { data } = matter(rawContent);

      const slug = data.slug || file.replace(/\.mdx$/, "");
      const camelName = toCamelCase(slug);

      // 📦 For posts.json
      posts.push({
        ...data,
        slug,
        excerpt: data.excerpt || "",
        date: data.date || null,
        tags: data.tags || [],
      });

      // 📦 For posts.js
      jsImports.push(`import ${camelName} from "./${file}";`);
      jsExports.push(`  "${slug}": ${camelName},`);
    }

    // ✍️ Write posts.json
    fs.writeFileSync(outputJson, JSON.stringify(posts, null, 2));
    console.log("✅ posts.json generated.");

    // ✍️ Write posts.js
    const jsContent = `// Auto-generated by generateBlogContent.js
${jsImports.join("\n")}

export default {
${jsExports.join("\n")}
};\n`;
    fs.writeFileSync(outputJs, jsContent);
    console.log("✅ posts.js generated.");
  } catch (err) {
    console.error("❌ Failed to generate blog content:", err.message);
    process.exit(1);
  }
}

generateBlogContent();
