// Auto-generated by generateBlogContent.js
import baobabSkinBenefits from "./baobab.mdx";
import benefitsOfPalmKernelOil from "./benefits-of-palm-kernel-oil.mdx";
import africanBlackSoap from "./black-soap.mdx";
import coldPressedOils from "./cold-pressed-oils.mdx";
import organicFarming from "./organic-farming.mdx";

export default {
  "baobab-skin-benefits": baobabSkinBenefits,
  "benefits-of-palm-kernel-oil": benefitsOfPalmKernelOil,
  "african-black-soap": africanBlackSoap,
  "cold-pressed-oils": coldPressedOils,
  "organic-farming": organicFarming,
};
